# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ejemplo_2026_nbdev',
                'doc_host': 'https://msalazarcgeo.github.io',
                'git_url': 'https://github.com/msalazarcgeo/ejemplo_2026_nbdev',
                'lib_path': 'ejemplo_2026_nbdev'},
  'syms': {'ejemplo_2026_nbdev.core': {'ejemplo_2026_nbdev.core.foo': ('core.html#foo', 'ejemplo_2026_nbdev/core.py')}}}
